export const apiKey = "36fc2f372af9e0f82430eaa06eb20b48"

export const top100Countries = [
    { city: "New York", country: "United States" },
    { city: "London", country: "United Kingdom" },
    { city: "Tokyo", country: "Japan" },
    { city: "Paris", country: "France" },
    { city: "Berlin", country: "Germany" },
    { city: "Madrid", country: "Spain" },
    { city: "Rome", country: "Italy" },
    { city: "Beijing", country: "China" },
    { city: "Moscow", country: "Russia" },
    { city: "Toronto", country: "Canada" },
    { city: "Sydney", country: "Australia" },
    { city: "Los Angeles", country: "United States" },
    { city: "Chicago", country: "United States" },
    { city: "Barcelona", country: "Spain" },
    { city: "Dubai", country: "United Arab Emirates" },
    { city: "Singapore", country: "Singapore" },
    { city: "Seoul", country: "South Korea" },
    { city: "Bangkok", country: "Thailand" },
    { city: "Mexico City", country: "Mexico" },
    { city: "Buenos Aires", country: "Argentina" },
    { city: "Lima", country: "Peru" },
    { city: "Santiago", country: "Chile" },
    { city: "Bogotá", country: "Colombia" },
    { city: "São Paulo", country: "Brazil" },
    { city: "Rio de Janeiro", country: "Brazil" },
    { city: "Johannesburg", country: "South Africa" },
    { city: "Cairo", country: "Egypt" },
    { city: "Istanbul", country: "Turkey" },
    { city: "Tehran", country: "Iran" },
    { city: "Karachi", country: "Pakistan" },
    { city: "Jakarta", country: "Indonesia" },
    { city: "Delhi", country: "India" },
    { city: "Mumbai", country: "India" },
    { city: "Manila", country: "Philippines" },
    { city: "Hanoi", country: "Vietnam" },
    { city: "Kuala Lumpur", country: "Malaysia" },
    { city: "Warsaw", country: "Poland" },
    { city: "Vienna", country: "Austria" },
    { city: "Prague", country: "Czech Republic" },
    { city: "Budapest", country: "Hungary" },
    { city: "Brussels", country: "Belgium" },
    { city: "Amsterdam", country: "Netherlands" },
    { city: "Zurich", country: "Switzerland" },
    { city: "Oslo", country: "Norway" },
    { city: "Stockholm", country: "Sweden" },
    { city: "Helsinki", country: "Finland" },
    { city: "Copenhagen", country: "Denmark" },
    { city: "Lisbon", country: "Portugal" },
    { city: "Athens", country: "Greece" },
    { city: "Dublin", country: "Ireland" },
    { city: "Edinburgh", country: "United Kingdom" },
    { city: "Manchester", country: "United Kingdom" },
    { city: "Birmingham", country: "United Kingdom" },
    { city: "Marseille", country: "France" },
    { city: "Lyon", country: "France" },
    { city: "Naples", country: "Italy" },
    { city: "Milan", country: "Italy" },
    { city: "Venice", country: "Italy" },
    { city: "Doha", country: "Qatar" },
    { city: "Abu Dhabi", country: "United Arab Emirates" },
    { city: "Auckland", country: "New Zealand" },
    { city: "Wellington", country: "New Zealand" },
    { city: "Tel Aviv", country: "Israel" },
    { city: "Jerusalem", country: "Israel" },
    { city: "Beirut", country: "Lebanon" },
    { city: "Amman", country: "Jordan" },
    { city: "Riyadh", country: "Saudi Arabia" },
    { city: "Jeddah", country: "Saudi Arabia" },
    { city: "Baghdad", country: "Iraq" },
    { city: "Kuwait City", country: "Kuwait" },
    { city: "Muscat", country: "Oman" },
    { city: "Cape Town", country: "South Africa" },
    { city: "Pretoria", country: "South Africa" },
    { city: "Algiers", country: "Algeria" },
    { city: "Casablanca", country: "Morocco" },
    { city: "Rabat", country: "Morocco" },
    { city: "Havana", country: "Cuba" },
    { city: "Kingston", country: "Jamaica" },
    { city: "San Juan", country: "Puerto Rico" },
    { city: "Panama City", country: "Panama" },
    { city: "San José", country: "Costa Rica" },
    { city: "Guatemala City", country: "Guatemala" },
    { city: "Quito", country: "Ecuador" },
    { city: "Caracas", country: "Venezuela" },
    { city: "La Paz", country: "Bolivia" },
    { city: "Montevideo", country: "Uruguay" },
    { city: "Asunción", country: "Paraguay" },
    { city: "Reykjavik", country: "Iceland" },
    { city: "Tallinn", country: "Estonia" },
    { city: "Riga", country: "Latvia" },
    { city: "Vilnius", country: "Lithuania" },
    { city: "Belgrade", country: "Serbia" },
    { city: "Zagreb", country: "Croatia" },
    { city: "Ljubljana", country: "Slovenia" },
    { city: "Bratislava", country: "Slovakia" },
    { city: "Skopje", country: "North Macedonia" },
    { city: "Sarajevo", country: "Bosnia and Herzegovina" },
    { city: "Tirana", country: "Albania" },
    { city: "Chisinau", country: "Moldova" },
    { city: "Yerevan", country: "Armenia" },
    { city: "Tbilisi", country: "Georgia" }
  ];
  